import {
  saveCustomRolesForOrganization,
  type CustomRoleDefinition,
} from "@/lib/custom-role-store";
import {
  saveDesignationsForOrganization,
  type DesignationDefinition,
} from "@/lib/designation-store";
import { replaceDemoModuleData } from "@/lib/demo-module-store";
import {
  saveRequisitionWorkflowConfig,
} from "@/lib/requisition-workflow-store";
import { saveUserCustomRoleKey } from "@/lib/user-custom-role-store";
import { saveUserPageAccess } from "@/lib/user-page-access-store";

const DEMO_ORG_KEY = "demo";

function daysAgo(days: number, hours = 0) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000 - hours * 60 * 60 * 1000).toISOString();
}

export async function seedDemoData() {
  const customRoles: CustomRoleDefinition[] = [
    {
      key: "PROCUREMENT_LEAD",
      name: "Procurement Lead",
      description: "Owns material requests, vendor follow-up, and dispatch coordination.",
      baseRole: "PURCHASER",
      pageAccess: ["overview", "requisition", "repair", "attendance", "profile", "newRequisition", "newRepairRequest", "newAttendance"],
      isSystem: false,
    },
    {
      key: "OPS_MANAGER",
      name: "Operations Manager",
      description: "Reviews field movement, attendance, and operational approvals.",
      baseRole: "MANAGER",
      pageAccess: ["overview", "requisition", "repair", "attendance", "salaryAdvance", "profile"],
      isSystem: false,
    },
    {
      key: "FINANCE_APPROVER",
      name: "Finance Approver",
      description: "Handles payment completion and salary advance follow-up.",
      baseRole: "ACCOUNTANT",
      pageAccess: ["overview", "requisition", "salaryAdvance", "profile", "newSalaryAdvance"],
      isSystem: false,
    },
    {
      key: "ADMIN_CONTROL",
      name: "Admin Control",
      description: "Runs system setup, access, and cross-module supervision.",
      baseRole: "ADMIN",
      pageAccess: [
        "overview",
        "roles",
        "designations",
        "workflow",
        "requisition",
        "repair",
        "attendance",
        "salaryAdvance",
        "users",
        "profile",
        "newRequisition",
        "newRepairRequest",
        "newAttendance",
        "newSalaryAdvance",
      ],
      isSystem: false,
    },
  ];

  const designations: DesignationDefinition[] = [
    {
      key: "PROCUREMENT_MANAGER",
      name: "Procurement Manager",
      description: "Senior buyer responsible for sourcing and delivery follow-up.",
      department: "Procurement",
      defaultCustomRoleKey: "PROCUREMENT_LEAD",
      isSystem: false,
    },
    {
      key: "OPERATIONS_MANAGER",
      name: "Operations Manager",
      description: "Coordinates sites, fleet movement, and operational approvals.",
      department: "Operations",
      defaultCustomRoleKey: "OPS_MANAGER",
      isSystem: false,
    },
    {
      key: "FINANCE_EXECUTIVE",
      name: "Finance Executive",
      description: "Tracks vendor payments and salary deduction schedules.",
      department: "Finance",
      defaultCustomRoleKey: "FINANCE_APPROVER",
      isSystem: false,
    },
    {
      key: "SYSTEM_ADMINISTRATOR",
      name: "System Administrator",
      description: "Handles organization setup, access control, and governance.",
      department: "Administration",
      defaultCustomRoleKey: "ADMIN_CONTROL",
      isSystem: false,
    },
  ];

  await saveCustomRolesForOrganization(DEMO_ORG_KEY, customRoles);
  await saveDesignationsForOrganization(DEMO_ORG_KEY, designations);
  await saveRequisitionWorkflowConfig(DEMO_ORG_KEY, {
    steps: [
      {
        key: "approval",
        label: "Operations Approval",
        description: "Operational validation before finance work starts.",
        enabled: true,
        roles: ["ADMIN_CONTROL", "OPS_MANAGER"],
      },
      {
        key: "payment",
        label: "Finance Clearance",
        description: "Confirm money movement or reimbursement readiness.",
        enabled: true,
        roles: ["ADMIN_CONTROL", "FINANCE_APPROVER"],
      },
      {
        key: "dispatch",
        label: "Dispatch Closure",
        description: "Complete dispatch or delivery after prior checkpoints.",
        enabled: true,
        roles: ["ADMIN_CONTROL", "PROCUREMENT_LEAD"],
      },
    ],
  });

  await saveUserCustomRoleKey("9999", "ADMIN_CONTROL");
  await saveUserCustomRoleKey("9998", "OPS_MANAGER");
  await saveUserCustomRoleKey("9997", "PROCUREMENT_LEAD");
  await saveUserCustomRoleKey("9996", "FINANCE_APPROVER");
  await saveUserPageAccess("9999", ["overview", "roles", "designations", "workflow", "requisition", "repair", "attendance", "salaryAdvance", "users", "profile", "newRequisition", "newRepairRequest", "newAttendance", "newSalaryAdvance"]);
  await saveUserPageAccess("9998", ["overview", "requisition", "repair", "attendance", "salaryAdvance", "profile"]);
  await saveUserPageAccess("9997", ["overview", "requisition", "repair", "attendance", "profile", "newRequisition", "newRepairRequest", "newAttendance"]);
  await saveUserPageAccess("9996", ["overview", "requisition", "salaryAdvance", "profile", "newSalaryAdvance"]);

  const requisitions = [
    {
      id: "1",
      requestId: "REQ-2026-0001",
      materialDescription: "Diesel fuel cards for mine-site transport fleet",
      description: "Urgent replenishment required for three active vehicles at Korba block.",
      siteAddress: "Korba Mine Site",
      quantity: 3,
      amount: 86000,
      priority: "URGENT",
      approvalStatus: "APPROVED",
      paymentStatus: "DONE",
      dispatchStatus: "DISPATCHED",
      status: "COMPLETED",
      vendorName: "Indian Oil Fleet Services",
      poDetails: "PO-2401",
      indentNo: "IND-7781",
      requiredFor: "",
      createdAt: daysAgo(8),
      approvedAt: daysAgo(7),
      paidAt: daysAgo(6),
      dispatchedAt: daysAgo(5),
      createdByName: "Paul Purchaser",
      approvedByName: "Mike Manager",
      paidByName: "Alice Accountant",
      dispatchedByName: "Paul Purchaser",
      approvalNotes: "Approved for uninterrupted vehicle movement.",
      paymentUtrNo: "UTR24011290",
      paymentMode: "NEFT",
      createdBy: { id: "9997", fullName: "Paul Purchaser" },
      billPhotoUrl: null,
      materialPhotoUrl: null,
      paymentPhotoUrl: null,
      vendorPaymentDetailsUrl: null,
    },
    {
      id: "2",
      requestId: "REQ-2026-0002",
      materialDescription: "Safety helmets and reflector jackets",
      description: "New induction batch at Bilaspur yard needs PPE before onboarding.",
      siteAddress: "Bilaspur Yard",
      quantity: 28,
      amount: 54200,
      priority: "HIGH",
      approvalStatus: "PENDING",
      paymentStatus: "NOT_DONE",
      dispatchStatus: "NOT_DISPATCHED",
      status: "SUBMITTED",
      vendorName: "SafeWorks India",
      poDetails: "",
      indentNo: "IND-7812",
      requiredFor: "",
      createdAt: daysAgo(2, 4),
      approvedAt: null,
      paidAt: null,
      dispatchedAt: null,
      createdByName: "Paul Purchaser",
      approvedByName: null,
      paidByName: null,
      dispatchedByName: null,
      approvalNotes: null,
      paymentUtrNo: null,
      paymentMode: null,
      createdBy: { id: "9997", fullName: "Paul Purchaser" },
      billPhotoUrl: null,
      materialPhotoUrl: null,
      paymentPhotoUrl: null,
      vendorPaymentDetailsUrl: null,
    },
    {
      id: "3",
      requestId: "REQ-2026-0003",
      materialDescription: "Spare tyres for highway support pickup",
      description: "One tyre burst and one reserve needed before interstate movement.",
      siteAddress: "Raipur Transport Office",
      quantity: 2,
      amount: 31800,
      priority: "NORMAL",
      approvalStatus: "APPROVED",
      paymentStatus: "NOT_DONE",
      dispatchStatus: "NOT_DISPATCHED",
      status: "APPROVED",
      vendorName: "JK Tyre",
      poDetails: "PO-2409",
      indentNo: "IND-7840",
      requiredFor: "",
      createdAt: daysAgo(4, 3),
      approvedAt: daysAgo(3, 20),
      paidAt: null,
      dispatchedAt: null,
      createdByName: "Paul Purchaser",
      approvedByName: "Mike Manager",
      paidByName: null,
      dispatchedByName: null,
      approvalNotes: "Proceed after finance confirms vendor account.",
      paymentUtrNo: null,
      paymentMode: null,
      createdBy: { id: "9997", fullName: "Paul Purchaser" },
      billPhotoUrl: null,
      materialPhotoUrl: null,
      paymentPhotoUrl: null,
      vendorPaymentDetailsUrl: null,
    },
    {
      id: "4",
      requestId: "REQ-2026-0004",
      materialDescription: "Office laptops for dispatch control room",
      description: "Two systems required for new shift-based tracking desk.",
      siteAddress: "Raipur HO",
      quantity: 2,
      amount: 124000,
      priority: "HIGH",
      approvalStatus: "APPROVED",
      paymentStatus: "DONE",
      dispatchStatus: "NOT_DISPATCHED",
      status: "PAID",
      vendorName: "Lenovo Enterprise",
      poDetails: "PO-2415",
      indentNo: "IND-7902",
      requiredFor: "",
      createdAt: daysAgo(6, 2),
      approvedAt: daysAgo(5, 10),
      paidAt: daysAgo(4, 8),
      dispatchedAt: null,
      createdByName: "Paul Purchaser",
      approvedByName: "Mike Manager",
      paidByName: "Alice Accountant",
      dispatchedByName: null,
      approvalNotes: "Approved under IT desk modernization budget.",
      paymentUtrNo: "UTR24014322",
      paymentMode: "RTGS",
      createdBy: { id: "9997", fullName: "Paul Purchaser" },
      billPhotoUrl: null,
      materialPhotoUrl: null,
      paymentPhotoUrl: null,
      vendorPaymentDetailsUrl: null,
    },
  ];

  const repairs = [
    {
      id: "3001",
      requestId: "RM-2026-0001",
      timestamp: daysAgo(5),
      createdAt: daysAgo(5),
      submittedAt: daysAgo(5),
      priority: "HIGH",
      repairRequisitionByName: "Paul Purchaser",
      warrantyStatus: "OUT_OF_WARRANTY",
      siteAddress: "Korba Mine Site",
      itemDescription: "Hydraulic jack replacement for HMV support truck",
      materialDescription: "Hydraulic jack replacement for HMV support truck",
      quantity: 1,
      repairVendorName: "Heavy Duty Garage",
      vendorName: "Heavy Duty Garage",
      repairStatusBeforePhoto: null,
      repairStatusAfterPhoto: null,
      expectedReturnDate: daysAgo(-2),
      repairStatus: "Under repair",
      returnedByName: null,
      dateOfReturn: null,
      dispatchStatus: "NOT_DISPATCHED",
      dispatchItemPhoto: null,
      paymentProofPhoto: null,
      billInvoicePhoto: null,
      dispatchSite: "Korba Mine Site",
      dispatchByName: null,
      dispatchDate: null,
      approvalStatus: "APPROVED",
      paymentStatus: "NOT_DONE",
      status: "APPROVED",
      createdBy: { fullName: "Paul Purchaser" },
      cardSubtitleInfo: JSON.stringify({
        repairRequisitionByName: "Paul Purchaser",
        warrantyStatus: "OUT_OF_WARRANTY",
        expectedReturnDate: daysAgo(-2),
        repairStatus: "Under repair",
        dispatchSite: "Korba Mine Site",
        contacts: [{ name: "Ravi Garage", phone: "9876543210", role: "Vendor" }],
      }),
    },
    {
      id: "3002",
      requestId: "RM-2026-0002",
      timestamp: daysAgo(10),
      createdAt: daysAgo(10),
      submittedAt: daysAgo(10),
      priority: "NORMAL",
      repairRequisitionByName: "Paul Purchaser",
      warrantyStatus: "IN_WARRANTY",
      siteAddress: "Bilaspur Yard",
      itemDescription: "GPS tracker issue for dispatch vehicle",
      materialDescription: "GPS tracker issue for dispatch vehicle",
      quantity: 1,
      repairVendorName: "FleetTrack Support",
      vendorName: "FleetTrack Support",
      repairStatusBeforePhoto: null,
      repairStatusAfterPhoto: null,
      expectedReturnDate: daysAgo(6),
      repairStatus: "Completed",
      returnedByName: "Mahesh Driver",
      dateOfReturn: daysAgo(6),
      dispatchStatus: "DELIVERED",
      dispatchItemPhoto: null,
      paymentProofPhoto: null,
      billInvoicePhoto: null,
      dispatchSite: "Bilaspur Yard",
      dispatchByName: "Paul Purchaser",
      dispatchDate: daysAgo(7),
      approvalStatus: "APPROVED",
      paymentStatus: "DONE",
      status: "COMPLETED",
      createdBy: { fullName: "Paul Purchaser" },
      cardSubtitleInfo: JSON.stringify({
        repairRequisitionByName: "Paul Purchaser",
        warrantyStatus: "IN_WARRANTY",
        expectedReturnDate: daysAgo(6),
        repairStatus: "Completed",
        returnedByName: "Mahesh Driver",
        dateOfReturn: daysAgo(6),
        dispatchSite: "Bilaspur Yard",
        dispatchByName: "Paul Purchaser",
        dispatchDate: daysAgo(7),
        deliveryStatus: "DELIVERED",
        deliveredAt: daysAgo(6),
        deliveredByName: "Paul Purchaser",
      }),
    },
    {
      id: "3003",
      requestId: "RM-2026-0003",
      timestamp: daysAgo(1, 6),
      createdAt: daysAgo(1, 6),
      submittedAt: daysAgo(1, 6),
      priority: "URGENT",
      repairRequisitionByName: "Paul Purchaser",
      warrantyStatus: "OUT_OF_WARRANTY",
      siteAddress: "Jagdalpur Route Checkpoint",
      itemDescription: "Battery drain issue in escort vehicle",
      materialDescription: "Battery drain issue in escort vehicle",
      quantity: 1,
      repairVendorName: "Om Auto Electricals",
      vendorName: "Om Auto Electricals",
      repairStatusBeforePhoto: null,
      repairStatusAfterPhoto: null,
      expectedReturnDate: daysAgo(-1),
      repairStatus: "Pending approval",
      returnedByName: null,
      dateOfReturn: null,
      dispatchStatus: "NOT_DISPATCHED",
      dispatchItemPhoto: null,
      paymentProofPhoto: null,
      billInvoicePhoto: null,
      dispatchSite: "Jagdalpur Route Checkpoint",
      dispatchByName: null,
      dispatchDate: null,
      approvalStatus: "PENDING",
      paymentStatus: "NOT_DONE",
      status: "SUBMITTED",
      createdBy: { fullName: "Paul Purchaser" },
      cardSubtitleInfo: JSON.stringify({
        repairRequisitionByName: "Paul Purchaser",
        warrantyStatus: "OUT_OF_WARRANTY",
        expectedReturnDate: daysAgo(-1),
        repairStatus: "Pending approval",
        dispatchSite: "Jagdalpur Route Checkpoint",
      }),
    },
  ];

  const attendance = [
    {
      id: "5001",
      requestId: "ATT-2026-0001",
      status: "APPROVED",
      approvalStatus: "APPROVED",
      timestamp: daysAgo(1, 2),
      createdAt: daysAgo(1, 2),
      submittedAt: daysAgo(1, 2),
      adminName: "Mike Manager",
      driverName: "Dharmendra (Dr. Hyva)",
      fromSiteName: "Raipur Office",
      toSiteName: "Bijetala",
      fatherName: "NA",
      vehicleType: "HMV",
      vehicleName: "HYVA",
      vehicleNumber: "CG04XY4567",
      geoTagPhotoUrl: null,
      siteAddress: "Raipur Office",
      materialDescription: "Dharmendra (Dr. Hyva)",
      vendorName: "HYVA",
      cardSubtitleInfo: JSON.stringify({
        adminName: "Mike Manager",
        driverName: "Dharmendra (Dr. Hyva)",
        fromSiteName: "Raipur Office",
        toSiteName: "Bijetala",
        fatherName: "NA",
        vehicleType: "HMV",
        vehicleName: "HYVA",
        vehicleNumber: "CG04XY4567",
      }),
    },
    {
      id: "5002",
      requestId: "ATT-2026-0002",
      status: "PENDING",
      approvalStatus: "PENDING",
      timestamp: daysAgo(0, 6),
      createdAt: daysAgo(0, 6),
      submittedAt: daysAgo(0, 6),
      adminName: "Mike Manager",
      driverName: "Rakesh Tanker",
      fromSiteName: "Bilaspur Yard",
      toSiteName: "Raigarh Plant",
      fatherName: "Shyamlal",
      vehicleType: "TANKER",
      vehicleName: "Ashok Leyland",
      vehicleNumber: "CG10TR1190",
      geoTagPhotoUrl: null,
      siteAddress: "Bilaspur Yard",
      materialDescription: "Rakesh Tanker",
      vendorName: "Ashok Leyland",
      cardSubtitleInfo: JSON.stringify({
        adminName: "Mike Manager",
        driverName: "Rakesh Tanker",
        fromSiteName: "Bilaspur Yard",
        toSiteName: "Raigarh Plant",
        fatherName: "Shyamlal",
        vehicleType: "TANKER",
        vehicleName: "Ashok Leyland",
        vehicleNumber: "CG10TR1190",
      }),
    },
    {
      id: "5003",
      requestId: "ATT-2026-0003",
      status: "REJECTED",
      approvalStatus: "REJECTED",
      timestamp: daysAgo(3),
      createdAt: daysAgo(3),
      submittedAt: daysAgo(3),
      adminName: "Mike Manager",
      driverName: "Mohan Dumper",
      fromSiteName: "Korba Mine Site",
      toSiteName: "Fuel Bay",
      fatherName: "Ramcharan",
      vehicleType: "DUMPER",
      vehicleName: "BharatBenz",
      vehicleNumber: "CG08DP9001",
      geoTagPhotoUrl: null,
      siteAddress: "Korba Mine Site",
      materialDescription: "Mohan Dumper",
      vendorName: "BharatBenz",
      cardSubtitleInfo: JSON.stringify({
        adminName: "Mike Manager",
        driverName: "Mohan Dumper",
        fromSiteName: "Korba Mine Site",
        toSiteName: "Fuel Bay",
        fatherName: "Ramcharan",
        vehicleType: "DUMPER",
        vehicleName: "BharatBenz",
        vehicleNumber: "CG08DP9001",
      }),
    },
  ];

  const salaryAdvances = [
    {
      id: "8001",
      requestId: "SA-2026-0001",
      status: "APPROVED",
      approvalStatus: "APPROVED",
      entryTimestamp: daysAgo(12),
      createdAt: daysAgo(12),
      submittedAt: daysAgo(12),
      employeeName: "Abhishek Gupta",
      employeeCode: "15552",
      designation: "Purchase Assistant",
      department: "Purchase",
      currentSalary: 28500,
      totalAdvanceRequest: 8000,
      repaymentSchedule: "Deduct from Feb'26 salary",
      initialSlipPhotoUrl: null,
      totalAdditionalAdvances: 4258,
      remarks: "Emergency household medical support.",
      deductionHistory: [
        {
          id: "ded-1",
          deductionDate: daysAgo(3),
          deductionAmount: 12258,
          remark: "Deduct from Feb'26 salary",
        },
      ],
      totalDeducted: 12258,
      balanceAdvance: 0,
      materialDescription: "Abhishek Gupta",
      siteAddress: "Purchase",
      vendorName: "Purchase Assistant",
      amount: 8000,
      description: "Emergency household medical support.",
      cardSubtitleInfo: JSON.stringify({
        employeeName: "Abhishek Gupta",
        employeeCode: "15552",
        designation: "Purchase Assistant",
        department: "Purchase",
        currentSalary: 28500,
        totalAdvanceRequest: 8000,
        repaymentSchedule: "Deduct from Feb'26 salary",
        totalAdditionalAdvances: 4258,
        remarks: "Emergency household medical support.",
        deductionHistory: [
          {
            id: "ded-1",
            deductionDate: daysAgo(3),
            deductionAmount: 12258,
            remark: "Deduct from Feb'26 salary",
          },
        ],
      }),
    },
    {
      id: "8002",
      requestId: "SA-2026-0002",
      status: "PENDING",
      approvalStatus: "PENDING",
      entryTimestamp: daysAgo(1),
      createdAt: daysAgo(1),
      submittedAt: daysAgo(1),
      employeeName: "Sunita Verma",
      employeeCode: "18310",
      designation: "Store Coordinator",
      department: "Stores",
      currentSalary: 24000,
      totalAdvanceRequest: 5000,
      repaymentSchedule: "Deduct in two salary cycles",
      initialSlipPhotoUrl: null,
      totalAdditionalAdvances: 0,
      remarks: "School fee support.",
      deductionHistory: [],
      totalDeducted: 0,
      balanceAdvance: 5000,
      materialDescription: "Sunita Verma",
      siteAddress: "Stores",
      vendorName: "Store Coordinator",
      amount: 5000,
      description: "School fee support.",
      cardSubtitleInfo: JSON.stringify({
        employeeName: "Sunita Verma",
        employeeCode: "18310",
        designation: "Store Coordinator",
        department: "Stores",
        currentSalary: 24000,
        totalAdvanceRequest: 5000,
        repaymentSchedule: "Deduct in two salary cycles",
        totalAdditionalAdvances: 0,
        remarks: "School fee support.",
        deductionHistory: [],
      }),
    },
    {
      id: "8003",
      requestId: "SA-2026-0003",
      status: "APPROVED",
      approvalStatus: "APPROVED",
      entryTimestamp: daysAgo(6),
      createdAt: daysAgo(6),
      submittedAt: daysAgo(6),
      employeeName: "Rajesh Kumar",
      employeeCode: "14004",
      designation: "Driver",
      department: "Transport",
      currentSalary: 21500,
      totalAdvanceRequest: 7000,
      repaymentSchedule: "Deduct from next salary",
      initialSlipPhotoUrl: null,
      totalAdditionalAdvances: 0,
      remarks: "Vehicle accident recovery support.",
      deductionHistory: [],
      totalDeducted: 0,
      balanceAdvance: 7000,
      materialDescription: "Rajesh Kumar",
      siteAddress: "Transport",
      vendorName: "Driver",
      amount: 7000,
      description: "Vehicle accident recovery support.",
      cardSubtitleInfo: JSON.stringify({
        employeeName: "Rajesh Kumar",
        employeeCode: "14004",
        designation: "Driver",
        department: "Transport",
        currentSalary: 21500,
        totalAdvanceRequest: 7000,
        repaymentSchedule: "Deduct from next salary",
        totalAdditionalAdvances: 0,
        remarks: "Vehicle accident recovery support.",
        deductionHistory: [],
      }),
    },
  ];

  replaceDemoModuleData({
    requisitions,
    repairs,
    attendance,
    salaryAdvances,
    requisitionCounter: requisitions.length,
    repairCounter: repairs.length,
    attendanceCounter: attendance.length,
    salaryAdvanceCounter: salaryAdvances.length,
  });

  return {
    organization: DEMO_ORG_KEY,
    credentials: [
      { email: "admin@example.com", password: "password123", role: "Admin Control" },
      { email: "manager@example.com", password: "password123", role: "Operations Manager" },
      { email: "purchaser@example.com", password: "password123", role: "Procurement Lead" },
      { email: "accountant@example.com", password: "password123", role: "Finance Approver" },
    ],
    counts: {
      requisitions: requisitions.length,
      repairs: repairs.length,
      attendance: attendance.length,
      salaryAdvances: salaryAdvances.length,
      customRoles: customRoles.length,
      designations: designations.length,
    },
  };
}
